### ISSUE TITLE
level resizing bug.

### ISSUE THREAD

**Issue by JettMonstersGoBoom** [deepnight/ldtk#391]
steps i took 
create world 2560x1280 . 
drew a bit on on the collision layer. 
resized world to 1280x1280. 
deleting and drawing now mismatch in certain areas. 

level file .

https://drive.google.com/file/d/1e_f8AqWxBp2q5bCFnBNdvjGJzse9UOvZ/view?usp=sharing

**Comment by deepnight** [comment]
When you resized, did you **type** values in the Level form, or did you drag the resize handles around the level?

**Comment by deepnight** [comment]
Ok found it, it'll be fixed in 0.8 . For now in 0.7.x, don't use the text inputs to resize a level, this will corrupt auto-layers. If this happens, a dirt temporary fix will be to:

1. open the rule panel of the corrupted layer
2. add a new rule on top of every others (ie. at the beginning of the rule list)
3. select any tile, leave the pattern grid empty
4. close the rule panel, LDtk will re-update all layers
5. open the rule panel again, 
6. delete the rule, 
7. close the panel.
8. LDtk will re-update all layers

In 0.8 update, there will be a debug menu to force all auto-layers re-evaluation, in case of emergency.

**Comment by JettMonstersGoBoom** [comment]
> When you resized, did you **type values in the Level form**, or did you **drag the resize handles** around the level?

yes this was manual entry.
