### ISSUE TITLE
MultiLines type is String in the Json

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#503]
While testing my fields, I noticed that both a multiline field's instance and definition is a type of `String` instead of expecting `MultiLines` like how LDtk displays which type the field is. Is this an expected behaviour?

In LDtk:
![image](https://user-images.githubusercontent.com/55564581/119278570-f570b100-bbda-11eb-901a-1454cbe3f1b3.png)

Json Instance:
![image](https://user-images.githubusercontent.com/55564581/119278653-6d3edb80-bbdb-11eb-9638-607966f8080c.png)

Json Definition:
![image](https://user-images.githubusercontent.com/55564581/119278588-1507d980-bbdb-11eb-922b-a1b0e7589f3f.png)

**Comment by deepnight** [comment]
Hmm 🤔 It would be better to have "*multilines*" as `__type` here, but changing this would mess up with existing importers, as this creates a new "type".

I'll add a new **advanced option** to export the specific new "Multilines" type (otherwise, it will just be "String"), and add a warning to make the change permanent in LDtk 1.2+
