### ISSUE TITLE
Linux redist

### ISSUE THREAD

**Issue by deepnight** [deepnight/ldtk#54]

**Comment by tgiannak** [comment]
I created packaging for Arch Linux for LEd [here](https://github.com/tgiannak/led-archlinux).

**Comment by Babouchot** [comment]
Hey 👋 
 I cloned the repo and ran "npm run pack-linux". I now have both a snap and an AppImage file. How would you like to proceed ?
I can provide you with the AppImage to add it to the current release (unfortunately github refuses me to link it to this message).
Or would you like to configure Travis to automatically upload build artifacts on github ?

**Comment by deepnight** [comment]
I honestly don't know much about Linux ecosystem, so I'll follow your recommendations here :)

I guess that having some **GitHub actions** ready would be the best approach, right?

**Comment by Babouchot** [comment]
Yeah, I don't know how you are distributing your Windows build right now, but I guess we can make Travis upload the AppImage on github when you tag a release. (AppImage should work on any linux distro whereas snap is more Ubuntu-centric).
I can make the configuration in a fork and send you a pull request when it's done if that's okay with you ?

**Comment by RPGillespie6** [comment]
Travis just uses a VM by default unless you specify a docker image with something like:

```
before_install:
  - docker pull deepnight/led

script:
  - docker run -v "$TRAVIS_BUILD_DIR":/mnt/workspace -w /mnt/workspace deepnight/led bash -c "cd app && npm install && cd - && haxe main.debug.hxml && haxe renderer.debug.hxml"
```

Dockerfile would be something like:
```
from haxe:4.1.4-alpine3.12

RUN haxelib git heaps https://github.com/HeapsIO/heaps.git && \
        haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs.git && \
        haxelib git electron https://github.com/tong/hxelectron.git && \
        haxelib git deepnightLibs https://github.com/deepnight/deepnightLibs.git

RUN apk add --update nodejs npm
```

That way you never have to install dependencies on whichever Linux CI or developer machine you want to build L-Ed on - you simply:

```
$ docker pull deepnight/led
$ cd led
$ docker run -it --rm -v "$PWD":/mnt/workspace -w /mnt/workspace -u $(id -u):$(id -g) deepnight/led
```

And you'll be dropped into a container that has all build dependencies

**Comment by RPGillespie6** [comment]
> Yeah, I don't know how you are distributing your Windows build right now, but I guess we can make Travis upload the AppImage on github when you tag a release. (AppImage should work on any linux distro whereas snap is more Ubuntu-centric).
> I can make the configuration in a fork and send you a pull request when it's done if that's okay with you ?

I agree, we should setup a trigger so that on tag -> build and upload linux package to github

**Comment by Babouchot** [comment]
Since all the builds are passing on Travis as is, is it really necessary to add a docker image when we could just get the artifact from the CI builds ? 
I also vote for AppImage, in my experience this has always been working fine on any distro. The ̀pack-linux` command also outputs a snap, but while it may not be difficult to provide both, I think providing only one build on each platform is less confusing for the users. So I would definitely opt for an AppImage, at least for github releases.

**Comment by RPGillespie6** [comment]
Docker image is not necessary for Travis, docker image is just nice to have for the following scenarios:
- Standardized portable build environment that works anywhere, including WSL
- Makes porting CI to a different platform down the road easier (i.e. Actions instead of Travis)
- Makes local Linux builds for developers/contributors easier (i.e. no need to check distro-specific repos to make sure haxe version >= 4.1, just install docker and you are good to go)

You are correct though, we don't need to do docker for this issue specifically. We could separate PR for docker build image down the road.

**Comment by Babouchot** [comment]
I can see that @sangohan already laid some work for the automated linux builds in #111 using github actions. I think that we should be using the same mechanism on all platform and just add a linux entry to the github actions matrix. Maybe Travis will be removed in the near future ?

**Comment by sangohan** [comment]
@Babouchot : yes, definitely looks to be easier to use github actions. I've prep'ed the ground work for it. The thing missing is to add in a check in the `main.yml` to see which OS the build is being run on, and run the appropriate npm command (the haxe part is the same). (see https://stackoverflow.com/questions/57946173/github-actions-run-step-on-specific-os for some sample).

**Comment by Babouchot** [comment]
Yes that was also what suggested @deepnight (sorry I did not understand at the time, I wasn't aware that Github launched its own CI/CD service and the name is not really telling so I mistook it for github hooks or that kind of thing).
I also think going with separate build files per platform is for the best.
