### ISSUE TITLE
Selecting/copying/pasting/moving groups of tiles

### ISSUE THREAD

**Issue by eliasdaler** [deepnight/ldtk#559]
Is it possible to select and move a group of tiles placed on a tile layer? Is it possible to copy/cut/paste the selection?
If not, this is a feature that I'd like to see. This is very important for re-arranging level layouts.

**Comment by deepnight** [comment]
Totally agree :)
That's an important feature, but also a very complex one, which requires some major rework before:
1. add a general copy/paste system (#134, available in 0.10.0)
2. rework the "Selection" system because the current one can't support copy/paste in its current approach 
3. add copy/paste support to this new Selection system which also means allowing "detached selections" (ie. data being selected but not really in the current level, like a ghost selection). This one is quite complicated :)

There's no estimated release date, but I hope to have it as part of "core" features (ie. before 1.0)
