### ISSUE TITLE
Changeable backup save location and/or append to filename timestamps

### ISSUE THREAD

**Issue by chosencharacters** [deepnight/ldtk#597]
Currently the backup save location is fixed as a subdirectory to where the LDTK level is. This causes issues in some programs (like OpenFL) which don't allow duplicate files (and will take all subdirectory files when trying to take something like 'assets/levels' so 'assets/levels/backups' will be taken as well.)

Another solution would be the ability to put a suffix like a timestamp on the backup file so it's never identical. So "levels-2-2-22-5-37.ldtk" or something

**Comment by deepnight** [comment]
Timestamps are now added to backup files but I guess it would be nice to be able to customize the backup location too 🤔

**Comment by chosencharacters** [comment]
I'm on 1.1.0 and it doesn't seem to be appending for me. But my project is also 500+ levels long in separate levels mode.

**Comment by deepnight** [comment]
There's no 1.1 :) 

This is what my backup folder in the project folder looks like:
![image](https://user-images.githubusercontent.com/1671695/152417405-a39c1210-3309-4446-bbf3-ec4f1530fcaa.png)

**Comment by chosencharacters** [comment]
Oh I meant append to each filename. The issue is duplicate filenames. And
uh sorry I had just woken up, I meant 1.0 :)

**Comment by jeremyfa** [comment]
+1 on being able to choose the backup location, either globally at LDtk level or a path relative to the project in project settings. My use case is: if I want to have an LDTK project in a Ceramic project's assets directory, edit it in place, it will also generate backup files that will also be processed by Ceramic assets system, which I don't want to include.

Being able to specify a relative directory would solve that issue because I can have the backups saved in a different directory that doesn't mess up my project's assets.

**Comment by deepnight** [comment]
This will be added in 1.2.6 or 1.3.0

**Comment by afk-mario** [comment]
Would be nice to change the extension as well so that custom importers don't try to import every backup file

**Comment by deepnight** [comment]
Available in 1.3.0
![image](https://user-images.githubusercontent.com/1671695/234001933-d91c8140-859d-41dd-9842-a551d6fbb4db.png)
