### ISSUE TITLE
[bug ]entity movement still limited by grid when grid mode of current layer is disable

### ISSUE THREAD

**Issue by JustusPan** [deepnight/ldtk#762]
when we disable the grid mode. we could place an entity freely in any position, but once we placed it, and then want to move it, the movement is still limited by grid.
![image](https://user-images.githubusercontent.com/10916383/207263695-27960a25-ddfd-4bf9-be73-21638fd2a2d4.png)

**Comment by deepnight** [comment]
Yes, that's super annoying and related to an old bad design decision I made when creating "Selection" of multiple objects. This should be fixed by the "Copy Paste" and "Selection" rework I have on my roadmap.

For now, as mentionned in #763, you may use the Extra Infos panel to adjust an object location.
